package model;

import java.io.Serializable;
import java.sql.Date;

public class Customer implements Serializable {
	
	private static final long serialVersionUID = -4325140103928816481L;
	
	private Integer customerId;
	private String firstName;
	private String lastName;
	private String email;
	private String passwordHash;
	private String address;
	private String contactNumber;
	private String aadhaarNumber;
	private String panNumber;
	private Date dob;
	private String gender;
	private String accountNumber;
	private String ifsc;
	private double accountBalance;
	private String salt;

	public Customer(
			Integer customerId, 
			String firstName,
			String lastName, 
			String email, 
			String passwordHash,
			String address, 
			String contactNumber,
			String aadhaarNumber,
			String panNumber, 
			Date dob, 
			String gender,
			String accountNumber, 
			String ifsc, 
			double accountBalance, 
			String salt
	) {
		this.customerId = customerId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.passwordHash = passwordHash;
		this.address = address;
		this.contactNumber = contactNumber;
		this.aadhaarNumber = aadhaarNumber;
		this.panNumber = panNumber;
		this.dob = dob;
		this.gender = gender;
		this.accountNumber = accountNumber;
		this.ifsc = ifsc;
		this.accountBalance = accountBalance;
		this.salt = salt;
	}

	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasswordHash() {
		return passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public String getAadhaarNumber() {
		return aadhaarNumber;
	}

	public void setAadhaarNumber(String aadhaarNumber) {
		this.aadhaarNumber = aadhaarNumber;
	}

	public String getPanNumber() {
		return panNumber;
	}

	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}

	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getIfsc() {
		return ifsc;
	}

	public void setIfsc(String ifsc) {
		this.ifsc = ifsc;
	}

	public double getAccountBalance() {
		return accountBalance;
	}

	public void setAccountBalance(double accountBalance) {
		this.accountBalance = accountBalance;
	}

	public String getSalt() {
		return salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Override
	public String toString() {
		return "Customer [customerId=" + customerId + ", firstName=" + firstName + ", lastName=" + lastName + ", email="
				+ email + ", passwordHash=" + passwordHash + ", address=" + address + ", contactNumber=" + contactNumber
				+ ", aadhaarNumber=" + aadhaarNumber + ", panNumber=" + panNumber + ", dob=" + dob + ", gender="
				+ gender + ", accountNumber=" + accountNumber + ", ifsc=" + ifsc + ", accountBalance=" + accountBalance
				+ ", salt=" + salt + "]";
	}

	public static String getSchema() {
		return "CREATE TABLE customers (" +
					"customer_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000, INCREMENT BY 1)," +
				    "first_name VARCHAR(50) NOT NULL," +
				    "last_name VARCHAR(50) NOT NULL," +
				    "email VARCHAR(100)," +
				    "password_hash VARCHAR(255)," +
				    "address VARCHAR(100)," +
				    "contact_number VARCHAR(10)," +
				    "aadhaar_number VARCHAR(12)," +
				    "pan_number VARCHAR(10)," +
				    "dob DATE," +
				    "gender VARCHAR(10)," +
				    "account_number VARCHAR(12)," +
				    "ifsc VARCHAR(12)," +
				    "account_balance DECIMAL(31, 2)," +
				    "salt VARCHAR(255)" +
			    ")";
	}
}
